language: erlang

env:
  - LUA=""
  - LUA="luajit"

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install libreadline-dev libncurses5-dev libpcre3 libpcre3-dev libpcre++-dev libssl-dev perl make
  - wget http://openresty.org/download/ngx_openresty-1.7.7.1.tar.gz
  - tar xzf ngx_openresty-1.7.7.1.tar.gz
  - cd ngx_openresty-1.7.7.1/
  - ./configure
  - make
  - sudo make install
  - cd ..

install:
  - sudo apt-get install sqlite3 libsqlite3-dev
  - sudo apt-get install luajit
  - export LUA_PATH='/usr/local/share/lua/5.1//?.lua;/usr/local/share/lua/5.1//?/init.lua;/home/vagrant/.luarocks/share/lua/5.1//?.lua;/home/vagrant/.luarocks/share/lua/5.1//?/init.lua;/usr/share/lua/5.1//?.lua;/usr/share/lua/6.1//?/init.lua;./?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/lib/lua/5.1/?.lua;/usr/local/lib/lua/5.1/?/init.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua'
  - wget http://luarocks.org/releases/luarocks-2.1.2.tar.gz
  - tar xzf luarocks-2.1.2.tar.gz
  - cd luarocks-2.1.2
  - ./configure
  - make build
  - sudo make install
  - cd ..
  - sudo luarocks install lrexlib-pcre PCRE_LIBDIR=$(dirname `sudo find / -type f -name "libpcre.so*" -print -quit`)
  - sudo luarocks install luasec OPENSSL_LIBDIR=$(dirname `sudo find / -type f -name "libssl.so*" -print -quit`)
  - sudo make global
  - make migrate

script: "make test-all"
